apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveryservice-deployment
  labels:
    app: deliveryservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deliveryservice
  template:
    metadata:
      labels:
        app: deliveryservice
    spec:
      containers:
        - name: deliveryservice
          image: pimaua/deliveryservice:bc3028e
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: pimaua-configmap
                  key: DELIVERY_SERVICE_APPLICATION_NAME
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: deliveryservice
spec:
  selector:
    app: deliveryservice
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deliveryservice-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/actions.redirect-to-https: >
      {"Type":"redirect","RedirectConfig":{"Protocol":"HTTPS","Port":"443","StatusCode":"HTTP_301"}}
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
spec:
  ingressClassName: alb
  rules:
    - host: delivery.pimapi.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redirect-to-https
                port:
                  name: use-annotation
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deliveryservice
                port:
                  number: 80