CREATE TABLE IF NOT EXISTS payment(
id INT AUTO_INCREMENT PRIMARY KEY,
order_id INT NOT NULL,
user_id INT NOT NULL,
amount DECIMAL(9,2) NOT NULL,
currency VARCHAR(50) NOT NULL,
status VARCHAR(50) NOT NULL,
stripe_payment_intent_id VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payment_method(
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
stripe_payment_method_id VARCHAR(255) NOT NULL,
type VARCHAR(50) NOT NULL,
brand VARCHAR(50) NOT NULL,
exp_month INT NOT NULL,
exp_year INT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stripe_customer(
user_id INT PRIMARY KEY,
stripe_customer_id VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);