server:
  port: 9000
spring:
  application:
    name: "paymentservice"

  datasource:
    url: jdbc:mysql://localhost:3309/paymentservicedb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: true
    connect-retries: 5

# feign to be removed when deploy to k8s
  cloud:
    openfeign:
      client:
        config:
          order-service:
            url: http://localhost:8081

    stream:
      bindings:
        orderStatus-out-0:   # producer binding
          destination: send-status
          content-type: application/json

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}




