spring:
  application:
    name: "coreservice"

  datasource:
    url: jdbc:mysql://localhost:3306/coreservicedb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
