name: CI-SpringBoot Microservices

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 7 * * 5"
  workflow_dispatch:

env:
  SERVICES: "coreservice,paymentservice,authservice,deliveryservice"
  DOCKER_IMAGE_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Run Unit Tests
        run: mvn test -Punit-tests -pl ${{ env.SERVICES }}

      - name: Package Microservices
        run: mvn clean package -DskipTests -pl ${{ env.SERVICES }}

      - name: Upload Packaged Microservices
        uses: actions/upload-artifact@v4
        with:
          name: packaged-microservices
          path: |
            coreservice/target/coreservice-*.jar
            paymentservice/target/paymentservice-*.jar
            authservice/target/authservice-*.jar
            deliveryservice/target/deliveryservice-*.jar

      - name: Log in to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Images
        if: github.event_name == 'push'
        run: |
          for service in ${SERVICES//,/ }; do
            dockerfile="./$service/Dockerfile"
            if [[ -f "$dockerfile" ]]; then
              IMAGE=${{ env.DOCKER_IMAGE_REPO }}/$service:latest
              echo "Building and pushing $IMAGE"
              docker build -t "$IMAGE" "./$service"
              docker push "$IMAGE"
            else
              echo "No Dockerfile for $service, skipping..."
            fi
          done
        shell: bash

  integration-tests:
    runs-on: ubuntu-latest
    needs: build
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -ptest --silent"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=60

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Packaged Microservices
        uses: actions/download-artifact@v4
        with:
          name: packaged-microservices

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Install MySQL Client
        run: sudo apt-get update && sudo apt-get install -y mysql-client
        shell: bash

      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..60}; do
            if mysqladmin ping -h mysql -uroot -ptest --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL... (Attempt $i/60)"
            sleep 2
          done

          if ! mysqladmin ping -h mysql -uroot -ptest --silent; then
            echo "MySQL failed to start"
            exit 1
          fi
        shell: bash

      - name: Initialize Database (Optional)
        run: |
          echo "Setting up database..."
          # mysql -h mysql -uroot -ptest testdb < path/to/your-schema.sql
        shell: bash

      - name: Start Microservices
        run: |
          echo "Starting microservices in background..."
          java -jar ./coreservice/target/coreservice-*.jar &
          PID_CORE=$!
          java -jar ./paymentservice/target/paymentservice-*.jar &
          PID_PAYMENT=$!
          java -jar ./authservice/target/authservice-*.jar &
          PID_AUTH=$!
          java -jar ./deliveryservice/target/deliveryservice-*.jar &
          PID_DELIVERY=$!

          echo "Waiting for services to be ready..."
          # Optional: replace with proper health checks
          sleep 30

          # Run integration tests
          mvn test -Pintegration-tests -pl ${{ env.SERVICES }}

          # Kill microservices after tests
          kill $PID_CORE $PID_PAYMENT $PID_AUTH $PID_DELIVERY
        shell: bash
