name: CI-SpringBoot Microservices

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 7 * * 5"
  workflow_dispatch:

env:
  SERVICES: "coreservice,paymentservice,authservice,deliveryservice"
  DOCKER_IMAGE_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Run Unit Tests
        run: mvn test -Punit-tests -pl ${{ env.SERVICES }}

      - name: Package Microservices
        run: mvn clean package -DskipTests -pl ${{ env.SERVICES }}

      - name: Log in to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Images
        if: github.event_name == 'push'
        run: |
          for service in ${SERVICES//,/ }; do
            dockerfile="./$service/Dockerfile"
            if [[ -f "$dockerfile" ]]; then
              IMAGE=${{ env.DOCKER_IMAGE_REPO }}/$service:latest
              echo "Building and pushing $IMAGE"
              docker build -t "$IMAGE" "./$service"
              docker push "$IMAGE"
            else
              echo "No Dockerfile for $service, skipping..."
            fi
          done
        shell: bash

  integration-tests:
    runs-on: ubuntu-latest
    needs: build
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -ptest --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: packaged-microservices

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Install MySQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
        shell: bash

      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -uroot -ptest --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL... (Attempt $i/30)"
            sleep 2
          done
          
          if ! mysqladmin ping -h 127.0.0.1 -uroot -ptest --silent; then
            echo "MySQL failed to start after multiple attempts."
            exit 1
          fi
        shell: bash

      - name: Run Integration Tests
        run: mvn test -Pintegration-tests -pl ${{ env.SERVICES }}
