name: CI-SpringBoot Microservices

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v5

      # Set up JDK 17 with Maven cache
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # Run ONLY unit tests for coreService + paymentService
      - name: Run unit tests
        run: mvn -pl coreService,paymentService test -DskipITs

      # Package microservices (skip all tests here to save time)
      - name: Package microservices
        run: mvn -B package -DskipTests

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build and push Docker images
      - name: Build and push Docker images
        run: |
          for service in coreService paymentService; do
            IMAGE=${{ secrets.DOCKER_HUB_USERNAME }}/$service
            echo "Building and pushing $IMAGE:latest"
            docker build -t $IMAGE:latest $service
            docker push $IMAGE:latest
          done
